server.port=8081
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.cache=false

# MongoDB Cloud Connection (Atlas Cluster0)
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.7hqqywi.mongodb.net/nexuschat?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
