server.port=${PORT:8081}
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.cache=false

# MongoDB Cloud Connection (Atlas Cluster0)
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.7hqqywi.mongodb.net/nexuschat?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

gemini.api.key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}
